"use strict"

/**
 * @author Yao Kan KOUASSI
 * @date Jan 2, 2023
 * @abstract Mini Game - You have 3 chances to guess a random number between 0 and 10 generated by the computer. Would you be able to win the game?
 * @const tries Number number of chances minus 1 - counter starts at 0
 * @var win Boolean maintains the game status - won or lost
 * @var computerNumber Number random number between 0 and 10, generated by the computer and reset at the start of every new game
 * @var attempts Number number of attempts already done - limit : @const tries
 * @function playTheGame starts the game
 * @function compareNumbers compares the number entered by player against the number generated by the computer
 */

const tries = 2
let win, computerNumber, attempts

/**
 * @description launch the game and handle user input and game status
 * @returns {undefined}
 */
function playTheGame() {
    if (!confirm("Would you like to play the game?"))
        alert("No problem, Goodbye")
    else {
        let input
        attempts = 0
        win = false
        computerNumber = Math.floor(Math.random() * 10)
        console.log(`Computer Number: ${computerNumber}`)

        do {
            do {
                input = prompt("Enter a number between 0 and 10: ")
                if(null === input)
                    return
                if (isNaN(input))
                    alert("Sorry Not a number")
            } while (isNaN(input) || (!isNaN(input) && (Number(input) < 0 || Number(input) > 10)))

            attempts++
            win = compareNumbers(input, computerNumber)
        } while (!win && attempts <= tries)
    }
}

/**
 * @description compare the number entered by player against the number generated by the computer and alert the result
 * @param {number} userNumber the number entered by the player
 * @param {number} computerNumber the random number generated by the computer
 * @returns {boolean} true if the player entered the correct number, false otherwise
 */
function compareNumbers(userNumber, computerNumber) {
    if (userNumber == computerNumber) {
        alert("WINNER")
        return true
    } else {
        alert(userNumber > computerNumber ? "Your number is bigger than the computer's, guess again" : "Your number is smaller than the computer's, guess again")
    }
    if (attempts > tries) {
        alert("Out of chances")
    }
    return false
}